# Generated by Django 3.0.8 on 2020-07-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20200716_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.CharField(blank=True, choices=[('1', '15'), ('2', '17'), ('3', '20'), ('4', '21'), ('5', '22'), ('6', '23'), ('7', '24')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(blank=True, choices=[('1', '15'), ('2', '17'), ('3', '20'), ('4', '21'), ('5', '22'), ('6', '23'), ('7', '24')], default=0, max_length=50, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.CharField(blank=True, choices=[('1', '11'), ('2', '12'), ('3', '14'), ('4', '15'), ('5', '16'), ('6', '17'), ('7', '18'), ('8', '19'), ('9', '20')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(blank=True, choices=[('1', '11'), ('2', '12'), ('3', '14'), ('4', '15'), ('5', '16'), ('6', '17'), ('7', '18'), ('8', '19'), ('9', '20')], default=0, max_length=50, verbose_name='開始時間'),
        ),
    ]
