# Generated by Django 3.0.8 on 2020-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20200718_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
