# Generated by Django 3.0.7 on 2020-06-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200602_2131'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('need_pa', models.IntegerField(default=0)),
                ('base_pa_a', models.IntegerField(default=0)),
                ('base_pa_b', models.IntegerField(default=0)),
                ('base_pa_c', models.IntegerField(default=0)),
                ('shops', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Shops')),
            ],
        ),
    ]
