# Generated by Django 3.0.7 on 2020-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200602_2131'),
        ('app', '0002_shop_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_config',
            name='date',
        ),
        migrations.AlterField(
            model_name='shop_config',
            name='base_pa_a',
            field=models.IntegerField(default=0, verbose_name='平日'),
        ),
        migrations.AlterField(
            model_name='shop_config',
            name='base_pa_b',
            field=models.IntegerField(default=0, verbose_name='祝前'),
        ),
        migrations.AlterField(
            model_name='shop_config',
            name='base_pa_c',
            field=models.IntegerField(default=0, verbose_name='土日'),
        ),
        migrations.CreateModel(
            name='Shop_config_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_need', models.IntegerField(default=0, verbose_name='必要人数')),
                ('date', models.DateField(verbose_name='日付')),
                ('shops', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Shops')),
            ],
        ),
    ]
