# Generated by Django 3.0.7 on 2020-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200628_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_config_day',
            name='day_need',
            field=models.IntegerField(verbose_name='必要人数'),
        ),
    ]
