# Generated by Django 3.0.7 on 2020-06-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200602_2131'),
        ('app', '0004_auto_20200629_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_config_day',
            name='shops',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='register.Shops', verbose_name='店舗'),
        ),
    ]
