# Generated by Django 3.0.7 on 2020-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200629_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_config',
            name='need_pa',
        ),
        migrations.AlterField(
            model_name='shop_config_day',
            name='day_need',
            field=models.IntegerField(default=0, verbose_name='必要人数'),
        ),
    ]
