# Generated by Django 3.0.8 on 2020-07-15 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2010, 1, 1, 0, 0), verbose_name='入店日'),
        ),
    ]
