# Generated by Django 3.0.4 on 2020-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_name',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='shop_name',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='入店日'),
        ),
    ]
