# Generated by Django 3.0.4 on 2020-05-22 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200522_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_name',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='shop_name',
            name='start_date',
        ),
        migrations.AddField(
            model_name='shop_name',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='生年月日'),
        ),
    ]
