# Generated by Django 3.0.4 on 2020-05-22 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200522_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_name',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='入店日'),
        ),
    ]
