# Generated by Django 3.0.4 on 2020-06-02 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_shop_name_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_name',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='shop_name',
            name='shop',
            field=models.CharField(blank=True, choices=[('1', '目黒'), ('2', '狛江'), ('3', '神保町'), ('4', '上野広小路'), ('5', '北千住')], default=1, max_length=3, verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='shop_name',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='入店日'),
        ),
    ]
