# Generated by Django 3.0.4 on 2020-06-02 07:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200602_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, choices=[('1', '目黒'), ('2', '狛江'), ('3', '神保町'), ('4', '上野広小路'), ('5', '北千住')], default=1, max_length=3, verbose_name='店舗')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='生年月日')),
                ('start_day', models.DateField(blank=True, default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='入店日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop_name',
        ),
    ]
